// frontend/src/app/features/devices/devices.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-devices',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './devices.component.html'
})
export class DevicesComponent implements OnInit {
  
  // Datos reales extraídos de tu init.sql
  devices = signal([
    {
      logic_id: 'ESP32-001',
      mac: 'AA:BB:CC:11:22:33',
      alias: 'Dispositivo de Marta',
      status: 'active',
      battery: 95,
      owner: 'Marta Rövanpera',
      userId: 3
    },
    {
      logic_id: 'ESP32-002',
      mac: 'AA:BB:CC:11:22:34',
      alias: 'Dispositivo de Roberto',
      status: 'active',
      battery: 72,
      owner: 'Roberto Gómez Ruiz',
      userId: 4
    },
    {
      logic_id: 'ESP32-003',
      mac: 'AA:BB:CC:11:22:35',
      alias: 'Dispositivo de Ana',
      status: 'low battery',
      battery: 15, // Reflejamos el estado 'low battery' del SQL
      owner: 'Ana Sánchez Moreno',
      userId: 5
    }
  ]);

  ngOnInit(): void {}

  // Función para determinar el color de la batería visualmente
  getBatteryClass(level: number): string {
    if (level > 50) return 'bg-emerald-500';
    if (level > 20) return 'bg-amber-500';
    return 'bg-red-500';
  }
}
<div class="p-8 bg-slate-50 min-h-screen font-sans">
  <header class="mb-10">
    <h1 class="text-3xl font-black text-slate-800 tracking-tighter uppercase italic tracking-widest">Inventario de Hardware</h1>
    <p class="text-slate-500 font-medium italic">Monitorización de sensores IoT y estado de autonomía</p>
  </header>

  <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
    <div *ngFor="let dev of devices()" class="bg-white rounded-[2.5rem] p-8 border border-slate-100 shadow-sm hover:shadow-xl transition-all group relative overflow-hidden">
      
      <div class="flex justify-between items-start mb-6">
        <div class="p-3 bg-purple-50 rounded-2xl text-purple-600 text-xl group-hover:scale-110 transition-transform">💾</div>
        <div class="flex items-center gap-2 bg-slate-50 px-3 py-1.5 rounded-full border border-slate-100">
          <span class="text-[10px] font-black text-slate-500">{{ dev.battery }}%</span>
          <div class="w-8 h-3.5 bg-slate-200 rounded-sm p-0.5">
            <div [class]="getBatteryClass(dev.battery)" [style.width.%]="dev.battery" class="h-full rounded-sm"></div>
          </div>
        </div>
      </div>

      <div class="mb-6">
        <h3 class="text-xl font-black text-slate-800 tracking-tight">{{ dev.logic_id }}</h3>
        <p class="text-[10px] font-black text-purple-500 uppercase tracking-widest mb-4">{{ dev.alias }}</p>
        
        <div class="space-y-2">
          <div class="flex items-center gap-2">
            <span class="text-[9px] font-black text-slate-400 uppercase tracking-widest w-16">Asignado a:</span>
            <span class="text-xs font-bold text-slate-700">{{ dev.owner }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[9px] font-black text-slate-400 uppercase tracking-widest w-16">Dirección MAC:</span>
            <span class="text-[10px] font-mono font-bold text-slate-400">{{ dev.mac }}</span>
          </div>
        </div>
      </div>

      <div class="pt-6 border-t border-slate-50 flex justify-between items-center">
        <div class="flex items-center gap-2">
          <div [ngClass]="dev.status === 'active' ? 'bg-emerald-500' : 'bg-red-500'" class="w-2 h-2 rounded-full animate-pulse"></div>
          <span class="text-[9px] font-black uppercase tracking-widest" [ngClass]="dev.status === 'active' ? 'text-emerald-600' : 'text-red-600'">
            {{ dev.status }}
          </span>
        </div>
        <button class="text-blue-600 text-[10px] font-black uppercase tracking-widest hover:underline transition-all">Configurar</button>
      </div>
    </div>
  </div>
</div>

// frontend/app/dashboard/admin/devices/page.tsx
'use client';

import { Smartphone, Plus, Settings, Cpu } from 'lucide-react';

export default function AdminDevicesManagement() {
  // Mocks basados en tu tabla SQL 'device'
  const dispositivos = [
    { id: 1, alias: 'Collar Abuelo', mac: 'AA:BB:CC:DD', status: 'active', device_id_logic: 'ESP-001' },
    { id: 2, alias: 'Pulsera María', mac: '11:22:33:44', status: 'low battery', device_id_logic: 'ESP-002' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 tracking-tight">Inventario Global</h1>
          <p className="text-slate-500 text-sm">Control de hardware (Tabla SQL: device)</p>
        </div>
        <button className="bg-blue-600 text-white px-4 py-2 rounded-xl flex items-center gap-2 hover:bg-blue-700 transition shadow-sm font-bold text-sm">
          <Plus size={18} /> Registrar ESP32
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {dispositivos.map((d) => (
          <div key={d.id} className="bg-white p-5 rounded-2xl border border-slate-200 flex justify-between items-center shadow-sm hover:shadow-md transition">
            <div className="flex items-center gap-4">
              <div className={`p-3 rounded-xl ${d.status === 'active' ? 'bg-green-50 text-green-600' : 'bg-red-50 text-red-600'}`}>
                <Cpu size={24} />
              </div>
              <div>
                <h3 className="font-bold text-slate-800">{d.alias}</h3>
                <p className="text-[10px] font-mono text-slate-400">LOGIC_ID: {d.device_id_logic} | MAC: {d.mac}</p>
              </div>
            </div>
            <div className="flex flex-col items-end gap-2">
              <span className={`text-[9px] font-black px-2 py-1 rounded uppercase ${
                d.status === 'active' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
              }`}>{d.status}</span>
              <button className="text-slate-400 hover:text-blue-600"><Settings size={16} /></button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
