// frontend/app/dashboard/admin/users/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { 
  Search, UserPlus, X, Save, Mail, Shield, 
  User as UserIcon, Activity, Smartphone, 
  Edit2, Trash2, ChevronDown, Lock, UserCircle 
} from 'lucide-react';

export default function UsersManagementPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [users, setUsers] = useState<any[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // 1. Carga inicial de usuarios
  useEffect(() => {
    const fetchInitialUsers = async () => {
      try {
        const mockUsers = [
          { id: 1, name: 'Admin', surnames: 'Principal', email: 'admin@sistema.com', roleId: 1 },
          { id: 2, name: 'Juan', surnames: 'Pérez', email: 'juan.cuidador@email.com', roleId: 2 },
          { id: 3, name: 'María', surnames: 'García', email: 'maria.paciente@email.com', roleId: 3 },
        ];
        setUsers(mockUsers);
      } catch (error) {
        console.error("Error cargando usuarios:", error);
      }
    };
    fetchInitialUsers();
  }, []);

  const handleDelete = (id: number) => {
    if (confirm('¿Está seguro de que desea eliminar este registro médico?')) {
      setUsers(prev => prev.filter(user => user.id !== id));
    }
  };

  const handleEdit = (user: any) => {
    alert(`Modo edición para: ${user.name}`);
  };

  const filteredUsers = users.filter(user => 
    `${user.name} ${user.surnames} ${user.email}`.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-800 tracking-tight">Gestión de Usuarios</h1>
          <p className="text-sm text-slate-500 font-medium">Administración de personal y pacientes</p>
        </div>
        <button 
          onClick={() => setIsModalOpen(true)}
          className="flex items-center gap-2 bg-blue-700 hover:bg-blue-800 text-white px-6 py-3 rounded-xl font-bold text-sm transition-all shadow-md active:scale-95"
        >
          <UserPlus size={18} />
          Nuevo Usuario
        </button>
      </div>

      <div className="relative">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
        <input 
          type="text"
          placeholder="Filtrar por nombre..."
          className="w-full pl-12 pr-4 py-4 bg-white border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 text-sm text-slate-900 font-medium"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200">
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase w-20 text-center">ID</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase">Información</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase">Rol</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase text-right">Acciones</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredUsers.map((user) => (
                <tr key={user.id} className="hover:bg-blue-50/30 transition-colors group">
                  <td className="px-6 py-4 text-center text-xs font-medium text-slate-400">
                    {user.id.toString().padStart(4, '0')}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-lg bg-blue-100 flex items-center justify-center text-blue-700 font-bold text-sm uppercase">
                        {user.name ? user.name[0] : 'U'}{user.surnames ? user.surnames[0] : ''}
                      </div>
                      <div>
                        <p className="font-bold text-slate-800 text-sm leading-none">{user.name} {user.surnames}</p>
                        <p className="text-xs text-slate-500 mt-1">{user.email}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <RoleBadge roleId={user.roleId} />
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex justify-end gap-1">
                      <button onClick={() => handleEdit(user)} className="p-2 text-slate-400 hover:text-blue-700 rounded-lg transition-all"><Edit2 size={15} /></button>
                      <button onClick={() => handleDelete(user.id)} className="p-2 text-slate-400 hover:text-red-600 rounded-lg transition-all"><Trash2 size={15} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {isModalOpen && (
        <AddUserModal 
          onClose={() => setIsModalOpen(false)} 
          onSuccess={(newUser: any) => {
            // USAMOS UNA FUNCIÓN DE ACTUALIZACIÓN PARA ASEGURARNOS DE TENER EL ESTADO MÁS RECIENTE
            setUsers((prevUsers) => [...prevUsers, newUser]);
          }}
        />
      )}
    </div>
  );
}

function AddUserModal({ onClose, onSuccess }: any) {
  const [formData, setFormData] = useState({ name: '', surnames: '', email: '', password: '', roleId: 3 });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const response = await fetch('http://localhost:4000/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (!response.ok) throw new Error(data.message || 'Error en el registro');

      // IMPORTANTE: El objeto que enviamos a onSuccess debe tener la estructura de la tabla
      const userToAdd = {
        id: data.user?.id || Math.floor(Math.random() * 1000) + 10,
        name: formData.name,
        surnames: formData.surnames,
        email: formData.email,
        roleId: formData.roleId
      };

      onSuccess(userToAdd);
      alert("Registro completado con éxito.");
      onClose(); // Cerramos el modal después de todo
    } catch (error: any) {
      alert(error.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-[2px]">
      <div className="bg-white w-full max-w-lg rounded-xl shadow-2xl border border-slate-200 overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="px-8 py-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
          <div>
            <h2 className="text-lg font-bold text-slate-800 tracking-tight uppercase">Alta de Nuevo Usuario</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white rounded-lg text-slate-400 transition-colors"><X size={20} /></button>
        </div>

        <form onSubmit={handleSubmit} className="p-8 space-y-5">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="text-[11px] font-bold text-slate-600 uppercase">Nombre</label>
              <input required className="w-full px-4 py-3 bg-white border border-slate-200 rounded-lg text-sm text-slate-900 font-semibold" 
                onChange={e => setFormData({...formData, name: e.target.value})} value={formData.name} />
            </div>
            <div className="space-y-1.5">
              <label className="text-[11px] font-bold text-slate-600 uppercase">Apellidos</label>
              <input required className="w-full px-4 py-3 bg-white border border-slate-200 rounded-lg text-sm text-slate-900 font-semibold" 
                onChange={e => setFormData({...formData, surnames: e.target.value})} value={formData.surnames} />
            </div>
          </div>
          <div className="space-y-1.5">
            <label className="text-[11px] font-bold text-slate-600 uppercase">Email Corporativo</label>
            <div className="relative text-slate-900">
              <Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <input type="email" required className="w-full pl-9 pr-4 py-3 bg-white border border-slate-200 rounded-lg text-sm font-semibold" 
                onChange={e => setFormData({...formData, email: e.target.value})} value={formData.email} />
            </div>
          </div>
          <div className="space-y-1.5">
            <label className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Contraseña Temporal</label>
            <div className="relative text-slate-900">
              <Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <input type="password" required className="w-full pl-9 pr-4 py-3 bg-white border border-slate-200 rounded-lg text-sm font-semibold" 
                onChange={e => setFormData({...formData, password: e.target.value})} value={formData.password} />
            </div>
          </div>
          <div className="space-y-1.5">
            <label className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Rol de Seguridad</label>
            <div className="relative text-slate-900">
              <Shield className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <select className="w-full pl-9 pr-10 py-3 bg-white border border-slate-200 rounded-lg text-sm font-bold appearance-none cursor-pointer" 
                value={formData.roleId} onChange={e => setFormData({...formData, roleId: Number(e.target.value)})}>
                <option value={1}>Administrador</option>
                <option value={2}>Personal Médico</option>
                <option value={3}>Paciente</option>
              </select>
              <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" size={18} />
            </div>
          </div>

          <div className="flex gap-3 pt-4">
            <button type="button" onClick={onClose} className="flex-1 px-4 py-3 border border-slate-200 text-slate-600 rounded-lg font-bold text-xs uppercase hover:bg-slate-50 transition-all">Cancelar</button>
            <button type="submit" disabled={isSubmitting} className="flex-1 bg-blue-700 hover:bg-blue-800 text-white font-bold py-3 rounded-lg transition-all shadow-md flex items-center justify-center gap-2 text-xs uppercase">
              {isSubmitting ? <Activity className="animate-spin" size={16} /> : <Save size={16} />}
              Finalizar Registro
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function RoleBadge({ roleId }: { roleId: number }) {
  const roles: any = {
    1: { label: 'Administrador', color: 'bg-slate-100 text-slate-700 border-slate-200', icon: <Shield size={12} /> },
    2: { label: 'Personal Médico', color: 'bg-blue-50 text-blue-700 border-blue-100', icon: <Activity size={12} /> },
    3: { label: 'Paciente', color: 'bg-emerald-50 text-emerald-700 border-emerald-100', icon: <UserCircle size={12} /> }
  };
  const role = roles[roleId] || { label: 'Usuario', color: 'bg-slate-50 text-slate-500 border-slate-100', icon: null };
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded border text-[11px] font-bold ${role.color}`}>
      {role.icon} {role.label}
    </span>
  );
}

// frontend/src/app/features/users/users.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { UserService } from '../../core/services/user.service';
import { User } from '../../core/models/user.models';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './users.component.html'
})
export class UsersComponent implements OnInit {
  private userService = inject(UserService);

  users: User[] = [];
  filteredUsers: User[] = [];
  
  searchTerm: string = '';
  sortAsc: boolean = true;
  currentPage: number = 1;
  pageSize: number = 10;

  // Estado del Modal/Formulario
  isModalOpen = false;
  isEditing = false; 
  selectedUser: Partial<User> = {};

  ngOnInit() {
    this.loadUsers();
  }

  // Getter para generar las filas vacías que faltan hasta llegar a 10
  get skeletonRows() {
    const currentCount = this.paginatedUsers.length;
    const remaining = this.pageSize - currentCount;
    return remaining > 0 ? Array(remaining).fill(0) : [];
  }

  loadUsers() {
    this.userService.getUsers().subscribe({
      next: (data: any) => {
        if (Array.isArray(data)) {
          this.users = data;
        } else if (data && data.users && Array.isArray(data.users)) {
          this.users = data.users;
        } else {
          this.users = [];
        }
        this.applyFilters();
      },
      error: (err) => console.error('Error al conectar con el backend:', err)
    });
  }

  applyFilters() {
    const search = this.searchTerm.toLowerCase().trim();
    
    let result = this.users.filter(u => 
      u.name?.toLowerCase().includes(search) ||
      u.surnames?.toLowerCase().includes(search) ||
      u.email?.toLowerCase().includes(search) ||
      u.phone_num?.includes(search)
    );

    result.sort((a, b) => {
      const nameA = (a.name || '').toLowerCase();
      const nameB = (b.name || '').toLowerCase();
      return this.sortAsc ? nameA.localeCompare(nameB) : nameB.localeCompare(nameA);
    });

    this.filteredUsers = result;
    this.currentPage = 1; 
  }

  openCreateModal() {
    this.isEditing = false;
    // Forzamos el tipo a User para evitar error con 'password'
    this.selectedUser = {
      role_id: 3,
      name: '',
      surnames: '',
      email: '',
      password: '',
      phone_num: ''
    } as User; 
    this.isModalOpen = true;
  }

  openEditModal(user: User) {
    this.isEditing = true;
    this.selectedUser = { ...user };
    this.isModalOpen = true;
  }

  closeModal() {
    this.isModalOpen = false;
    this.selectedUser = {};
  }

  saveUser() {
    if (this.isEditing && this.selectedUser.id) {
      this.userService.updateUser(this.selectedUser.id, this.selectedUser).subscribe({
        next: () => {
          this.loadUsers();
          this.closeModal();
        },
        error: (err) => console.error('Error al actualizar:', err)
      });
    } else {
      this.userService.createUser(this.selectedUser as User).subscribe({
        next: () => {
          this.loadUsers();
          this.closeModal();
        },
        error: (err) => console.error('Error al crear usuario:', err)
      });
    }
  }

  deleteUser(id: number) {
    if (confirm('¿Estás seguro de eliminar este usuario?')) {
      this.userService.deleteUser(id).subscribe({
        next: () => this.loadUsers(),
        error: (err) => console.error('Error al borrar:', err)
      });
    }
  }

  get paginatedUsers() {
    const start = (this.currentPage - 1) * this.pageSize;
    return this.filteredUsers.slice(start, start + this.pageSize);
  }

  get totalPages() {
    return Math.ceil(this.filteredUsers.length / this.pageSize) || 1;
  }

  toggleSort() {
    this.sortAsc = !this.sortAsc;
    this.applyFilters();
  }

  getRoleName(role_id?: number): string {
    const roles: { [key: number]: string } = { 1: 'Admin', 2: 'Cuidador', 3: 'Usuario' };
    return roles[role_id || 0] || 'Sin Rol';
  }
}
<div class="p-8 bg-slate-50 min-h-screen font-sans">
  
  <div class="flex justify-between items-center mb-10">
    <div>
      <h1 class="text-3xl font-black text-slate-800 tracking-tighter uppercase italic">Gestión de Usuarios</h1>
      <p class="text-slate-500 font-medium">Administra los accesos y roles del sistema</p>
    </div>
    
    <button (click)="openCreateModal()" 
            class="bg-blue-600 hover:bg-blue-500 text-white px-8 py-4 rounded-2xl font-black text-xs uppercase tracking-widest transition-all shadow-xl shadow-blue-200 flex items-center gap-2">
      <span>➕</span> Nuevo Usuario
    </button>
  </div>

  <div class="bg-white p-4 rounded-3xl border border-slate-100 shadow-sm mb-8 flex gap-4 items-center">
    <span class="text-slate-400 ml-2">🔍</span>
    <input type="text" [(ngModel)]="searchTerm" (input)="applyFilters()" 
           placeholder="Buscar por nombre, email o teléfono..." 
           class="flex-1 bg-transparent border-none focus:ring-0 text-sm font-medium text-slate-600 outline-none">
  </div>

  <div class="bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden">
    <table class="w-full text-left border-collapse">
      <thead>
        <tr class="bg-slate-900 text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">
          <th class="px-8 py-6 cursor-pointer hover:text-white transition-colors" (click)="toggleSort()">
            Nombre Completo {{sortAsc ? '↑' : '↓'}}
          </th>
          <th class="px-8 py-6">Email</th>
          <th class="px-8 py-6">Teléfono</th>
          <th class="px-8 py-6 text-center">Rol</th>
          <th class="px-8 py-6 text-right">Acciones</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-slate-50">
        
        <tr *ngFor="let user of paginatedUsers" class="hover:bg-slate-50/50 transition-colors group h-[72px]">
          <td class="px-8 py-5">
            <p class="font-black text-slate-800 tracking-tight">{{user.name}} {{user.surnames}}</p>
          </td>
          <td class="px-8 py-5 text-sm font-medium text-slate-500 italic">{{user.email}}</td>
          <td class="px-8 py-5 text-sm font-bold text-slate-400">{{user.phone_num || '---'}}</td>
          <td class="px-8 py-5 text-center">
            <span [ngClass]="{
              'bg-blue-100 text-blue-600': user.role_id === 1,
              'bg-purple-100 text-purple-600': user.role_id === 2,
              'bg-emerald-100 text-emerald-600': user.role_id === 3
            }" class="px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-widest">
              {{getRoleName(user.role_id)}}
            </span>
          </td>
          <td class="px-8 py-5 text-right space-x-2">
            <button (click)="openEditModal(user)" class="p-2 hover:bg-blue-50 text-blue-600 rounded-xl transition-colors">📝</button>
            <button (click)="deleteUser(user.id)" class="p-2 hover:bg-red-50 text-red-500 rounded-xl transition-colors">🗑️</button>
          </td>
        </tr>

        <tr *ngFor="let empty of skeletonRows" class="h-[72px] opacity-40">
          <td class="px-8 py-5">
            <div class="h-4 w-32 bg-slate-100 rounded-full animate-pulse"></div>
          </td>
          <td class="px-8 py-5">
            <div class="h-4 w-40 bg-slate-50 rounded-full"></div>
          </td>
          <td class="px-8 py-5">
            <div class="h-4 w-24 bg-slate-50 rounded-full"></div>
          </td>
          <td class="px-8 py-5 flex justify-center items-center">
            <div class="h-6 w-16 bg-slate-100 rounded-lg"></div>
          </td>
          <td class="px-8 py-5"></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="flex justify-between items-center mt-6 px-4">
    <p class="text-xs font-bold text-slate-400 uppercase tracking-widest">
      Página {{currentPage}} de {{totalPages}}
    </p>
    <div class="flex gap-2">
      <button [disabled]="currentPage === 1" (click)="currentPage = currentPage - 1"
              class="px-4 py-2 bg-white border border-slate-200 rounded-xl text-xs font-bold disabled:opacity-30 transition-all">
        Anterior
      </button>
      <button [disabled]="currentPage === totalPages" (click)="currentPage = currentPage + 1"
              class="px-4 py-2 bg-slate-900 text-white rounded-xl text-xs font-bold disabled:opacity-30 transition-all shadow-lg">
        Siguiente
      </button>
    </div>
  </div>

  <div *ngIf="isModalOpen" class="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
    <div class="bg-white w-full max-w-lg rounded-[3rem] shadow-2xl p-10 animate-in zoom-in duration-300">
      
      <div class="flex justify-between items-center mb-8">
        <h2 class="text-2xl font-black text-slate-800 tracking-tighter uppercase italic">
          {{ isEditing ? 'Editar Usuario' : 'Nuevo Usuario' }}
        </h2>
        <button (click)="closeModal()" class="text-slate-400 hover:text-slate-800 text-xl font-bold transition-colors">✕</button>
      </div>

      <form (ngSubmit)="saveUser()" #userForm="ngForm" class="space-y-6">
        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Nombre</label>
            <input type="text" name="name" [(ngModel)]="selectedUser.name" required class="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-3 text-sm focus:ring-2 focus:ring-blue-500/20 outline-none transition-all">
          </div>
          <div>
            <label class="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Apellidos</label>
            <input type="text" name="surnames" [(ngModel)]="selectedUser.surnames" class="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-3 text-sm focus:ring-2 focus:ring-blue-500/20 outline-none transition-all">
          </div>
        </div>

        <div>
          <label class="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Email</label>
          <input type="email" name="email" [(ngModel)]="selectedUser.email" required class="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-3 text-sm focus:ring-2 focus:ring-blue-500/20 outline-none transition-all">
        </div>

        <div *ngIf="!isEditing">
          <label class="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Password Provisional</label>
          <input type="password" name="password" [(ngModel)]="selectedUser.password" required class="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-3 text-sm focus:ring-2 focus:ring-blue-500/20 outline-none transition-all">
        </div>

        <div>
          <label class="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Rol en el Sistema</label>
          <select name="role_id" [(ngModel)]="selectedUser.role_id" required class="w-full bg-slate-50 border border-slate-100 rounded-2xl px-5 py-3 text-sm focus:ring-2 focus:ring-blue-500/20 outline-none appearance-none transition-all">
            <option [value]="1">Administrador</option>
            <option [value]="2">Cuidador / Sanitario</option>
            <option [value]="3">Paciente (Usuario Final)</option>
          </select>
        </div>

        <button type="submit" [disabled]="!userForm.valid"
                class="w-full bg-slate-900 text-white py-4 rounded-2xl font-black text-xs uppercase tracking-[0.2em] hover:bg-blue-600 transition-all shadow-lg disabled:opacity-30 mt-4">
          {{ isEditing ? 'Guardar Cambios' : 'Registrar en Base de Datos' }}
        </button>
      </form>
    </div>
  </div>
</div>
