// frontend/src/app/features/users/admin-users/users.component.ts
import { Component, inject, OnInit, signal, computed } from '@angular/core';
import { FormsModule } from '@angular/forms'; // Eliminamos CommonModule
import { UserService } from '../../../core/services/user.service';
import { User } from '../../../core/models/auth.models';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [FormsModule], // 🔥 Solo FormsModule, usaremos bindings nativos
  templateUrl: './users.component.html'
})
export class UsersComponent implements OnInit {
  private userService = inject(UserService);

  // --- SIGNALS DE ESTADO ---
  users = signal<User[]>([]);
  searchTerm = signal<string>('');
  sortAsc = signal<boolean>(true);
  currentPage = signal<number>(1);
  pageSize = 10;

  isModalOpen = signal(false);
  selectedUser = signal<Partial<User>>({});

  ngOnInit() {
    this.loadUsers();
  }

  // --- LÓGICA REACTIVA ---
  
  cuidadores = computed(() => 
    this.users().filter(u => u.role_id === 2)
  );

  filteredUsers = computed(() => {
    const search = this.searchTerm().toLowerCase().trim();
    const isAsc = this.sortAsc();
    
    let result = this.users().filter(u => 
      u.name?.toLowerCase().includes(search) ||
      u.surnames?.toLowerCase().includes(search) ||
      u.email?.toLowerCase().includes(search) ||
      u.phone_num?.includes(search)
    );

    return result.sort((a, b) => {
      const nameA = (a.name || '').toLowerCase();
      const nameB = (b.name || '').toLowerCase();
      return isAsc ? nameA.localeCompare(nameB) : nameB.localeCompare(nameA);
    });
  });

  paginatedUsers = computed(() => {
    const start = (this.currentPage() - 1) * this.pageSize;
    return this.filteredUsers().slice(start, start + this.pageSize);
  });

  totalPages = computed(() => Math.ceil(this.filteredUsers().length / this.pageSize) || 1);

  // --- ACCIONES OPERATIVAS ---

  loadUsers() {
    this.userService.getUsers().subscribe({
      next: (data) => this.users.set(data),
      error: (err) => console.error('Error Backend:', err)
    });
  }

  saveUser() {
    const userData = this.selectedUser();
    if (userData.id) {
      this.userService.updateUser(userData.id, userData).subscribe({
        next: () => { 
          this.loadUsers(); 
          this.closeModal(); 
        },
        error: (err) => alert('Error al actualizar: ' + err.error.message)
      });
    }
  }

  deleteUser(id: number) {
    if (confirm('¿Estás seguro de eliminar este usuario permanentemente?')) {
      this.userService.deleteUser(id).subscribe({
        next: () => this.loadUsers(),
        error: (err) => alert('Error al borrar: ' + err.error.message)
      });
    }
  }

  // --- HELPERS ---

  openEditModal(user: User) {
    this.selectedUser.set({ ...user });
    this.isModalOpen.set(true);
  }

  closeModal() {
    this.isModalOpen.set(false);
    this.selectedUser.set({});
  }

  toggleSort() {
    this.sortAsc.update(val => !val);
  }

  getRoleName(role_id?: number): string {
    const roles: Record<number, string> = { 1: 'Admin', 2: 'Cuidador', 3: 'Usuario' };
    return roles[role_id || 0] || 'Sin Rol';
  }
}
<div class="p-4 md:p-8 bg-slate-50 min-h-screen font-sans">
  
  <header class="mb-8">
    <h1 class="text-2xl md:text-3xl font-black text-slate-800 tracking-tighter uppercase italic leading-none">Gestión de Usuarios</h1>
    <p class="text-slate-500 font-medium text-[10px] md:text-xs mt-2 italic uppercase tracking-widest leading-none">Administración Real · Base de Datos PostgreSQL</p>
  </header>

  <div class="bg-white p-4 rounded-3xl border border-slate-100 shadow-sm mb-6 flex gap-4 items-center">
    <span class="text-slate-400 ml-2">🔍</span>
    <input type="text" 
            [ngModel]="searchTerm()" 
            (ngModelChange)="searchTerm.set($event); currentPage.set(1)" 
            placeholder="Buscar por nombre, email o teléfono..." 
            class="flex-1 bg-transparent border-none focus:ring-0 text-sm font-medium text-slate-600 outline-none">
  </div>

  <div class="grid grid-cols-1 gap-4 md:hidden mb-8">
    @for (user of paginatedUsers(); track user.id) {
      <div class="bg-white p-6 rounded-[2.5rem] border border-slate-100 shadow-sm relative overflow-hidden">
        <div class="flex justify-between items-start mb-4">
          <div>
            <p class="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">ID #{{user.id}}</p>
            <h3 class="font-black text-slate-800 text-lg leading-tight">{{user.name}} {{user.surnames}}</h3>
          </div>
          <span class="px-3 py-1 rounded-xl text-[8px] font-black uppercase tracking-widest border"
                [class.bg-blue-50]="user.role_id === 1" [class.text-blue-600]="user.role_id === 1" [class.border-blue-100]="user.role_id === 1"
                [class.bg-purple-50]="user.role_id === 2" [class.text-purple-600]="user.role_id === 2" [class.border-purple-100]="user.role_id === 2"
                [class.bg-emerald-50]="user.role_id === 3" [class.text-emerald-600]="user.role_id === 3" [class.border-emerald-100]="user.role_id === 3">
            {{getRoleName(user.role_id)}}
          </span>
        </div>
        
        <div class="space-y-1 mb-6">
          <p class="text-xs font-bold text-slate-500 italic">{{user.email}}</p>
          <p class="text-[10px] font-black text-blue-500 uppercase">{{user.phone_num || '-- SIN TELÉFONO --'}}</p>
        </div>

        <div class="flex gap-2">
          <button (click)="openEditModal(user)" class="flex-1 py-4 bg-slate-50 text-slate-700 rounded-2xl font-black text-[10px] uppercase tracking-widest active:bg-slate-200 transition-colors">Editar</button>
          <button (click)="deleteUser(user.id)" class="flex-1 py-4 bg-red-50 text-red-500 rounded-2xl font-black text-[10px] uppercase tracking-widest active:bg-red-100 transition-colors">Borrar</button>
        </div>
      </div>
    }
  </div>

  <div class="hidden md:block bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden mb-8">
    <table class="w-full text-left border-collapse">
      <thead>
        <tr class="bg-slate-900 text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">
          <th class="px-8 py-6 cursor-pointer hover:text-white transition-colors" (click)="toggleSort()">
            Nombre Completo {{sortAsc() ? '↑' : '↓'}}
          </th>
          <th class="px-8 py-6">Contacto</th>
          <th class="px-8 py-6 text-center">Rol Sistema</th>
          <th class="px-8 py-6 text-right">Acciones</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-slate-50">
        @for (user of paginatedUsers(); track user.id) {
          <tr class="hover:bg-slate-50/50 transition-colors group">
            <td class="px-8 py-5">
              <p class="font-black text-slate-800 tracking-tight text-sm">#{{user.id}} - {{user.name}} {{user.surnames}}</p>
            </td>
            <td class="px-8 py-5">
              <p class="text-xs font-bold text-slate-500 italic">{{user.email}}</p>
              <p class="text-[10px] font-black text-blue-500 mt-1 uppercase">{{user.phone_num || '--'}}</p>
            </td>
            <td class="px-8 py-5 text-center">
              <span class="px-3 py-1.5 rounded-xl text-[9px] font-black uppercase tracking-widest border"
                    [class.bg-blue-50]="user.role_id === 1" [class.text-blue-600]="user.role_id === 1" [class.border-blue-100]="user.role_id === 1"
                    [class.bg-purple-50]="user.role_id === 2" [class.text-purple-600]="user.role_id === 2" [class.border-purple-100]="user.role_id === 2"
                    [class.bg-emerald-50]="user.role_id === 3" [class.text-emerald-600]="user.role_id === 3" [class.border-emerald-100]="user.role_id === 3">
                {{getRoleName(user.role_id)}}
              </span>
            </td>
            <td class="px-8 py-5 text-right space-x-2">
              <button (click)="openEditModal(user)" class="p-3 hover:bg-blue-50 text-blue-600 rounded-2xl transition-all">✏️</button>
              <button (click)="deleteUser(user.id)" class="p-3 hover:bg-red-50 text-red-500 rounded-2xl transition-all">🗑️</button>
            </td>
          </tr>
        }
      </tbody>
    </table>
  </div>

  <div class="flex flex-col sm:flex-row justify-between items-center mt-6 px-4 gap-4">
    <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Página {{currentPage()}} de {{totalPages()}}</p>
    <div class="flex gap-3 w-full sm:w-auto">
      <button [disabled]="currentPage() === 1" (click)="currentPage.set(currentPage() - 1)" class="flex-1 sm:flex-none px-6 py-3 bg-white border border-slate-200 rounded-2xl text-[10px] font-black uppercase disabled:opacity-30 transition-all">Anterior</button>
      <button [disabled]="currentPage() === totalPages()" (click)="currentPage.set(currentPage() + 1)" class="flex-1 sm:flex-none px-6 py-3 bg-slate-900 text-white rounded-2xl text-[10px] font-black uppercase disabled:opacity-30 transition-all shadow-lg">Siguiente</button>
    </div>
  </div>

  @if (isModalOpen()) {
    <div class="fixed inset-0 bg-slate-900/70 backdrop-blur-md z-50 flex items-center justify-center p-4">
      <div class="bg-white w-full max-w-lg rounded-[2.5rem] md:rounded-[3.5rem] shadow-2xl p-8 md:p-12 animate-in zoom-in duration-300 max-h-[90vh] overflow-y-auto">
        
        <div class="flex justify-between items-center mb-10">
          <h2 class="text-2xl font-black text-slate-800 tracking-tighter uppercase italic">Editar Perfil</h2>
          <button (click)="closeModal()" class="w-10 h-10 flex items-center justify-center bg-slate-50 rounded-full text-slate-400 hover:text-red-500 transition-colors">✕</button>
        </div>

        <form (ngSubmit)="saveUser()" #userForm="ngForm" class="space-y-5">
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <input type="text" name="name" [(ngModel)]="selectedUser().name" required placeholder="Nombre" 
                   class="w-full bg-slate-50 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-blue-500/20 outline-none">
            <input type="text" name="surnames" [(ngModel)]="selectedUser().surnames" placeholder="Apellidos" 
                   class="w-full bg-slate-50 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-blue-500/20 outline-none">
          </div>

          <input type="email" name="email" [(ngModel)]="selectedUser().email" required placeholder="Email" 
                 class="w-full bg-slate-50 border-none rounded-2xl px-5 py-4 text-sm font-bold focus:ring-2 focus:ring-blue-500/20 outline-none">

          <div class="pt-4 border-t border-slate-100">
            <label class="block text-[9px] font-black text-slate-400 uppercase tracking-widest ml-4 mb-2">Asignar Rol</label>
            <select name="role_id" [(ngModel)]="$any(selectedUser()).role_id" required 
                    class="w-full bg-slate-50 border-none rounded-2xl px-5 py-4 text-sm font-bold outline-none appearance-none cursor-pointer">
              <option [value]="1">Administrador</option>
              <option [value]="2">Cuidador</option>
              <option [value]="3">Usuario</option>
            </select>
          </div>

          @if (selectedUser().role_id == 3) {
            <div class="animate-in slide-in-from-top-2">
              <label class="block text-[9px] font-black text-slate-400 uppercase tracking-widest ml-4 mb-2">Cuidador Responsable</label>
              <select name="carer_id" [(ngModel)]="selectedUser().carer_id" 
                      class="w-full bg-blue-50/50 border-2 border-blue-100 rounded-2xl px-5 py-4 text-sm font-bold outline-none appearance-none cursor-pointer">
                <option [value]="null">-- Sin Cuidador Asignado --</option>
                @for (c of cuidadores(); track c.id) {
                  <option [value]="c.id">{{c.name}} {{c.surnames}}</option>
                }
              </select>
            </div>
          }

          <button type="submit" [disabled]="!userForm.valid"
                  class="w-full bg-slate-900 text-white py-5 rounded-4xl font-black text-[10px] uppercase tracking-[0.2em] hover:bg-blue-600 transition-all shadow-2xl mt-6 active:scale-95">
            Sincronizar con Base de Datos
          </button>
        </form>
      </div>
    </div>
  }
</div>

// frontend/app/dashboard/admin/users/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { 
  Search, UserPlus, X, Save, Mail, Shield, 
  User as UserIcon, Activity, Smartphone, 
  Edit2, Trash2, ChevronDown, Lock, UserCircle 
} from 'lucide-react';

export default function UsersManagementPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [users, setUsers] = useState<any[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // 1. Carga inicial de usuarios
  useEffect(() => {
    const fetchInitialUsers = async () => {
      try {
        const mockUsers = [
          { id: 1, name: 'Admin', surnames: 'Principal', email: 'admin@sistema.com', roleId: 1 },
          { id: 2, name: 'Juan', surnames: 'Pérez', email: 'juan.cuidador@email.com', roleId: 2 },
          { id: 3, name: 'María', surnames: 'García', email: 'maria.paciente@email.com', roleId: 3 },
        ];
        setUsers(mockUsers);
      } catch (error) {
        console.error("Error cargando usuarios:", error);
      }
    };
    fetchInitialUsers();
  }, []);

  const handleDelete = (id: number) => {
    if (confirm('¿Está seguro de que desea eliminar este registro médico?')) {
      setUsers(prev => prev.filter(user => user.id !== id));
    }
  };

  const handleEdit = (user: any) => {
    alert(`Modo edición para: ${user.name}`);
  };

  const filteredUsers = users.filter(user => 
    `${user.name} ${user.surnames} ${user.email}`.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-800 tracking-tight">Gestión de Usuarios</h1>
          <p className="text-sm text-slate-500 font-medium">Administración de personal y pacientes</p>
        </div>
        <button 
          onClick={() => setIsModalOpen(true)}
          className="flex items-center gap-2 bg-blue-700 hover:bg-blue-800 text-white px-6 py-3 rounded-xl font-bold text-sm transition-all shadow-md active:scale-95"
        >
          <UserPlus size={18} />
          Nuevo Usuario
        </button>
      </div>

      <div className="relative">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
        <input 
          type="text"
          placeholder="Filtrar por nombre..."
          className="w-full pl-12 pr-4 py-4 bg-white border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 text-sm text-slate-900 font-medium"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200">
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase w-20 text-center">ID</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase">Información</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase">Rol</th>
                <th className="px-6 py-4 text-[11px] font-bold text-slate-500 uppercase text-right">Acciones</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredUsers.map((user) => (
                <tr key={user.id} className="hover:bg-blue-50/30 transition-colors group">
                  <td className="px-6 py-4 text-center text-xs font-medium text-slate-400">
                    {user.id.toString().padStart(4, '0')}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-lg bg-blue-100 flex items-center justify-center text-blue-700 font-bold text-sm uppercase">
                        {user.name ? user.name[0] : 'U'}{user.surnames ? user.surnames[0] : ''}
                      </div>
                      <div>
                        <p className="font-bold text-slate-800 text-sm leading-none">{user.name} {user.surnames}</p>
                        <p className="text-xs text-slate-500 mt-1">{user.email}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <RoleBadge roleId={user.roleId} />
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex justify-end gap-1">
                      <button onClick={() => handleEdit(user)} className="p-2 text-slate-400 hover:text-blue-700 rounded-lg transition-all"><Edit2 size={15} /></button>
                      <button onClick={() => handleDelete(user.id)} className="p-2 text-slate-400 hover:text-red-600 rounded-lg transition-all"><Trash2 size={15} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {isModalOpen && (
        <AddUserModal 
          onClose={() => setIsModalOpen(false)} 
          onSuccess={(newUser: any) => {
            // USAMOS UNA FUNCIÓN DE ACTUALIZACIÓN PARA ASEGURARNOS DE TENER EL ESTADO MÁS RECIENTE
            setUsers((prevUsers) => [...prevUsers, newUser]);
          }}
        />
      )}
    </div>
  );
}

function AddUserModal({ onClose, onSuccess }: any) {
  const [formData, setFormData] = useState({ name: '', surnames: '', email: '', password: '', roleId: 3 });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const response = await fetch('http://localhost:4000/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (!response.ok) throw new Error(data.message || 'Error en el registro');

      // IMPORTANTE: El objeto que enviamos a onSuccess debe tener la estructura de la tabla
      const userToAdd = {
        id: data.user?.id || Math.floor(Math.random() * 1000) + 10,
        name: formData.name,
        surnames: formData.surnames,
        email: formData.email,
        roleId: formData.roleId
      };

      onSuccess(userToAdd);
      alert("Registro completado con éxito.");
      onClose(); // Cerramos el modal después de todo
    } catch (error: any) {
      alert(error.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-[2px]">
      <div className="bg-white w-full max-w-lg rounded-xl shadow-2xl border border-slate-200 overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="px-8 py-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
          <div>
            <h2 className="text-lg font-bold text-slate-800 tracking-tight uppercase">Alta de Nuevo Usuario</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white rounded-lg text-slate-400 transition-colors"><X size={20} /></button>
        </div>

        <form onSubmit={handleSubmit} className="p-8 space-y-5">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="text-[11px] font-bold text-slate-600 uppercase">Nombre</label>
              <input required className="w-full px-4 py-3 bg-white border border-slate-200 rounded-lg text-sm text-slate-900 font-semibold" 
                onChange={e => setFormData({...formData, name: e.target.value})} value={formData.name} />
            </div>
            <div className="space-y-1.5">
              <label className="text-[11px] font-bold text-slate-600 uppercase">Apellidos</label>
              <input required className="w-full px-4 py-3 bg-white border border-slate-200 rounded-lg text-sm text-slate-900 font-semibold" 
                onChange={e => setFormData({...formData, surnames: e.target.value})} value={formData.surnames} />
            </div>
          </div>
          <div className="space-y-1.5">
            <label className="text-[11px] font-bold text-slate-600 uppercase">Email Corporativo</label>
            <div className="relative text-slate-900">
              <Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <input type="email" required className="w-full pl-9 pr-4 py-3 bg-white border border-slate-200 rounded-lg text-sm font-semibold" 
                onChange={e => setFormData({...formData, email: e.target.value})} value={formData.email} />
            </div>
          </div>
          <div className="space-y-1.5">
            <label className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Contraseña Temporal</label>
            <div className="relative text-slate-900">
              <Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <input type="password" required className="w-full pl-9 pr-4 py-3 bg-white border border-slate-200 rounded-lg text-sm font-semibold" 
                onChange={e => setFormData({...formData, password: e.target.value})} value={formData.password} />
            </div>
          </div>
          <div className="space-y-1.5">
            <label className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Rol de Seguridad</label>
            <div className="relative text-slate-900">
              <Shield className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <select className="w-full pl-9 pr-10 py-3 bg-white border border-slate-200 rounded-lg text-sm font-bold appearance-none cursor-pointer" 
                value={formData.roleId} onChange={e => setFormData({...formData, roleId: Number(e.target.value)})}>
                <option value={1}>Administrador</option>
                <option value={2}>Personal Médico</option>
                <option value={3}>Paciente</option>
              </select>
              <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" size={18} />
            </div>
          </div>

          <div className="flex gap-3 pt-4">
            <button type="button" onClick={onClose} className="flex-1 px-4 py-3 border border-slate-200 text-slate-600 rounded-lg font-bold text-xs uppercase hover:bg-slate-50 transition-all">Cancelar</button>
            <button type="submit" disabled={isSubmitting} className="flex-1 bg-blue-700 hover:bg-blue-800 text-white font-bold py-3 rounded-lg transition-all shadow-md flex items-center justify-center gap-2 text-xs uppercase">
              {isSubmitting ? <Activity className="animate-spin" size={16} /> : <Save size={16} />}
              Finalizar Registro
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function RoleBadge({ roleId }: { roleId: number }) {
  const roles: any = {
    1: { label: 'Administrador', color: 'bg-slate-100 text-slate-700 border-slate-200', icon: <Shield size={12} /> },
    2: { label: 'Personal Médico', color: 'bg-blue-50 text-blue-700 border-blue-100', icon: <Activity size={12} /> },
    3: { label: 'Paciente', color: 'bg-emerald-50 text-emerald-700 border-emerald-100', icon: <UserCircle size={12} /> }
  };
  const role = roles[roleId] || { label: 'Usuario', color: 'bg-slate-50 text-slate-500 border-slate-100', icon: null };
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded border text-[11px] font-bold ${role.color}`}>
      {role.icon} {role.label}
    </span>
  );
}
